# Generated by Django 5.1 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegIncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg1', models.CharField(choices=[('GEN', 'General'), ('BPL', 'BPL'), ('HAN', 'Handicap')], default='GEN', max_length=3, verbose_name='Leg 1 Category')),
                ('leg2', models.CharField(choices=[('GEN', 'General'), ('BPL', 'BPL'), ('HAN', 'Handicap')], default='GEN', max_length=3, verbose_name='Leg 2 Category')),
                ('leg3', models.CharField(choices=[('GEN', 'General'), ('BPL', 'BPL'), ('HAN', 'Handicap')], default='GEN', max_length=3, verbose_name='Leg 3 Category')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Income')),
            ],
            options={
                'verbose_name': 'Leg Income Model',
                'verbose_name_plural': 'Leg Income Models',
            },
        ),
    ]
