# Generated by Django 5.1 on 2025-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_incomesettingforwomenold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleIncomeSettingForBPLHandicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('BPL', 'BPL')], max_length=15, null=True)),
                ('income', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('previous_income', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incomesetting',
            name='child_one',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomesetting',
            name='child_three',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomesetting',
            name='child_two',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Normal', 'Normal'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=15, null=True),
        ),
    ]
