# Generated by Django 5.1 on 2025-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doubleincomesettingforbplhandicap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleincomesettingforbplhandicap',
            name='category',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=15, null=True),
        ),
    ]
