# Generated by Django 5.1 on 2025-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doubleincomesettingforbplhandicap_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleincomesettingforbplhandicap',
            name='category',
            field=models.CharField(blank=True, choices=[('BPL', 'BPL'), ('Handicap', 'Handicap')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='incomesettingforwomenold',
            name='category',
            field=models.CharField(blank=True, choices=[('Childhood (7-12 year)', 'Childhood (7-12 year)'), ('Teenager (13-18 years)', 'Teenager (13-18 years)'), ('Young Male (19-39 years)', 'Young Male (19-39 years)'), ('Young Female (19-39 years)', 'Young Female (19-39 years)'), ('Mature Male (40-59 years)', 'Mature Male (40-59 years)'), ('Mature Female (40-59 years)', 'Mature Female (40-59 years)'), ('Senior Citizen (60 years and above)', 'Senior Citizen (60 years and above)')], max_length=50, null=True),
        ),
    ]
