# Generated by Django 5.1 on 2025-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
