# Generated by Django 5.1 on 2025-01-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0002_product_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], default='ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment made by RazorPay', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom_product.useraddress'),
        ),
        migrations.AddField(
            model_name='product',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(related_name='cart_item', to='ecom_product.product'),
        ),
    ]
