# Generated by Django 5.1 on 2025-04-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0005_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
