# Generated by Django 5.1 on 2025-06-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0007_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
