# Generated by Django 5.1 on 2025-07-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0008_vendor_gst_number_vendor_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_product_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='tender_product/image/')),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('review', 'Under Review'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('tender_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
