# Generated by Django 5.1 on 2025-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0010_tenderbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderbid',
            name='negotiation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiation', 'Negotiation')], default='pending', max_length=20),
        ),
    ]
