# Generated by Django 5.1 on 2025-07-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0011_tenderbid_negotiation_message_tenderbid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
