# Generated by Django 5.1 on 2025-07-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0012_tender_quantity_tenderbid_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lists', to='ecom_product.tender')),
                ('tender_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lists', to='ecom_product.tenderbid')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lists', to='ecom_product.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RawProductListBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ecom_product.rawproductlist')),
            ],
        ),
    ]
