# Generated by Django 5.1 on 2025-08-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0013_rawproductlist_rawproductlistbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_status', models.CharField(choices=[('pending', 'Pending'), ('inspected', 'Inspected')], default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='ecom_product.rawproductlistbatch')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='ecom_product.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='ecom_product.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='FaultyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('received_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faulty_items', to='ecom_product.receivedorder')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('received_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_products', to='ecom_product.receivedorder')),
            ],
        ),
    ]
