# Generated by Django 5.1 on 2025-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0014_receivedorder_faultyitem_acceptedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedproduct',
            name='accepted_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faultyitem',
            name='faulty_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faultyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
