# Generated by Django 5.1 on 2025-08-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0015_acceptedproduct_accepted_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedorder',
            name='batch',
        ),
        migrations.AddField(
            model_name='receivedorder',
            name='raw_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='ecom_product.rawproductlist'),
            preserve_default=False,
        ),
    ]
