# Generated by Django 5.1 on 2025-08-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0016_remove_receivedorder_batch_receivedorder_raw_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='ecom_product.rawproductlistbatch'),
        ),
    ]
