# Generated by Django 5.1 on 2025-08-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0017_receivedorder_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_person_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='firm_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='firm_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_firm/images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website_app_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='vendor_products/images/')),
                ('size_packing', models.CharField(max_length=50)),
                ('unit_per_mks', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_quantity', models.PositiveIntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vedndor_product_details', to='ecom_product.vendor')),
            ],
        ),
    ]
