# Generated by Django 5.1 on 2025-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0018_vendor_contact_person_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproductdetails',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_products/images/'),
        ),
    ]
