# Generated by Django 5.1 on 2025-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0019_alter_vendorproductdetails_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='firm_mode',
            field=models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Dealer', 'Dealer'), ('Supplier', 'Supplier'), ('Agency', 'Agency'), ('Shopkeeper', 'Shopkeeper'), ('Exporter', 'Exporter'), ('Importer', 'Importer'), ('Contractor', 'Contractor'), ('Farmer', 'Farmer'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='other_option_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
